# Project information
site_name: Faculdade de Arquitetura e Urbanismo
site_author: Grupo 03
site_url: https://Requisitos-de-Software.github.io/2022.1-Faculdade-de-Arquitetura-e-Urbanismo

# Repository
repo_name: 2022.1-Faculdade-de-Arquitetura-e-Urbanismo
repo_url: https://github.com/Requisitos-de-Software/2022.1-Faculdade-de-Arquitetura-e-Urbanismo

theme:
  name: "material"
  language: "pt"
  logo: "assets/logo_faunb.png"
  palette:
    primary: "grey"
    accent: "light grey"
  font:
    text: "Montserrat"
    code: "sans-serif"

plugins:
  - mkdocs-video

# Content Menu
nav:
  - Início: index.md
  - Planejamento:
    - Cronograma de atividades: planejamento/cronograma-de-atividades.md
    - Análise dos sites:
      - Sites avaliados: planejamento/analiseSites/escolha-do-site.md
      - Site escolhido: planejamento/analiseSites/site-escolhido.md
    - Metodologia e processos: planejamento/metodologia-e-processos.md
    - Processo de design: planejamento/processo-de-design.md
  - Análise de Requisitos:
    - Perfil de Usuário: analise-de-requisitos/Perfil-de-usuario.md
    - Personas: analise-de-requisitos/personas.md
    - Aspectos éticos: analise-de-requisitos/aspectos-eticos.md
    - Análise de tarefas: analise-de-requisitos/analise-de-tarefas.md
    - Princípios Gerais: analise-de-requisitos/principios-gerais.md
    - Metas de Usabilidade: analise-de-requisitos/metas-de-usabilidade.md
  - Apresentações: apresentacoes.md

