# Project information
site_name: Faculdade de Arquitetura e Urbanismo
site_author: Grupo 03
site_url: https://Requisitos-de-Software.github.io/2022.1-Faculdade-de-Arquitetura-e-Urbanismo

# Repository
repo_name: 2022.1-Faculdade-de-Arquitetura-e-Urbanismo
repo_url: https://github.com/Requisitos-de-Software/2022.1-Faculdade-de-Arquitetura-e-Urbanismo

theme:
  name: "material"
  language: "pt"
  logo: "assets/logo_faunb.png"
  palette:
    primary: "grey"
    accent: "light grey"
  font:
    text: "Montserrat"
    code: "sans-serif"

plugins:
  - mkdocs-video

# Content Menu
nav:
  - In√≠cio: index.md
  - Planejamento: escolha-do-site.md
